services:
  client:
    build:
      context: ./packages/client
      dockerfile: Dockerfile
    container_name: app_client
    ports:
      - "8080:8080"
    volumes:
      - ./packages/client:/app/client
    environment:
      - NODE_ENV=development
    stdin_open: true
    tty: true

  server:
    build:
      context: ./packages/server
      dockerfile: Dockerfile
    container_name: app_server
    ports:
      - "3000:3000"
    volumes:
      - ./packages/server:/app/server
    stdin_open: true
    tty: true
